In [3]:
# ---------------------------------------------------------------------
# 0. Imports & data ----------------------------------------------------
# ---------------------------------------------------------------------
import numpy as np
import os
import pandas as pd
import statsmodels.api as sm
import hssm                           # 0.7.0+ recommended
# from your_rl_module import logp_jax_op, model_config   # <- your own
csvfile = os.path.join(os.getcwd(), "hddm2_fixed_final_2states.csv")
dataset = pd.read_csv(csvfile)           # <- path to your file

In [4]:
dataset

,Unnamed: 0,subj_idx,rt1,rt2,response1,response2,state1,state2,feedback,trial,cond,q_init,isleft1,isleft2,split_by
0,1,0.0,1.139,1.345,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.5,1.0,0.0,1.0
1,2,0.0,0.781,1.268,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
2,3,0.0,0.439,1.879,0.0,1.0,0.0,1.0,0.0,2.0,1.0,0.5,1.0,1.0,1.0
3,4,0.0,0.892,1.111,1.0,0.0,0.0,1.0,0.0,3.0,1.0,0.5,0.0,1.0,1.0
4,5,0.0,0.479,0.964,0.0,1.0,0.0,0.0,0.0,4.0,1.0,0.5,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29525,29526,107.0,0.411,0.366,1.0,1.0,0.0,0.0,1.0,292.0,1.0,0.5,0.0,1.0,1.0
29526,29527,107.0,0.688,0.802,1.0,1.0,0.0,1.0,0.0,293.0,1.0,0.5,1.0,0.0,1.0
29527,29528,107.0,0.328,0.340,0.0,0.0,0.0,0.0,0.0,294.0,1.0,0.5,1.0,0.0,1.0
29528,29529,107.0,0.308,0.399,1.0,1.0,0.0,1.0,1.0,295.0,1.0,0.5,1.0,0.0,1.0
29529,29530,107.0,0.648,0.513,1.0,1.0,0.0,1.0,1.0,296.0,1.0,0.5,0.0,1.0,1.0

In [6]:
df = dataset[dataset['subj_idx'] == 0.0]
df

,Unnamed: 0,subj_idx,rt1,rt2,response1,response2,state1,state2,feedback,trial,cond,q_init,isleft1,isleft2,split_by
0,1,0.0,1.139,1.345,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.5,1.0,0.0,1.0
1,2,0.0,0.781,1.268,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
2,3,0.0,0.439,1.879,0.0,1.0,0.0,1.0,0.0,2.0,1.0,0.5,1.0,1.0,1.0
3,4,0.0,0.892,1.111,1.0,0.0,0.0,1.0,0.0,3.0,1.0,0.5,0.0,1.0,1.0
4,5,0.0,0.479,0.964,0.0,1.0,0.0,0.0,0.0,4.0,1.0,0.5,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,289,0.0,0.313,0.953,0.0,1.0,0.0,0.0,0.0,288.0,1.0,0.5,1.0,0.0,1.0
289,290,0.0,0.748,0.629,0.0,0.0,0.0,0.0,1.0,289.0,1.0,0.5,0.0,1.0,1.0
290,291,0.0,0.570,0.563,0.0,0.0,0.0,1.0,1.0,290.0,1.0,0.5,0.0,0.0,1.0
291,292,0.0,0.556,0.863,0.0,0.0,0.0,0.0,1.0,291.0,1.0,0.5,1.0,1.0,1.0
292,293,0.0,0.480,0.819,0.0,0.0,0.0,0.0,1.0,292.0,1.0,0.5,1.0,1.0,1.0

In [7]:

def beta_transition_variance_conj(df, n_states=2, n_actions=2, a0=1.0, b0=1.0):
    """
    Parameters
    ----------
    df : DataFrame in chronological order with columns
            'action'  – first-stage choice   (0 … n_actions-1)
            'common'  – 1 if transition was common, 0 if rare
    n_actions : number of first-stage actions (usually 2)
    a0, b0    : prior counts for Beta(a0, b0). 1.0 gives uniform prior.

    Returns
    -------
    df_out  : df with new column 'trans_var'
    post_a, post_b : final Beta counts, shape (n_actions,)
    """

    num_states = n_states * (n_states - 1) // 2  # n choose 2

    # initialise Beta(a0,b0) for each action
    a = np.full((num_states,n_actions), a0, dtype=float)
    b = np.full((num_states,n_actions), b0, dtype=float)

    var_list = []

    for _, row in df.iterrows():
        # currstate = 
        s_t = int(row["state1"])  # 0 or 1
        a_t = int(row["action"])
        c_t = int(row["common"])           # 1=common, 0=rare

        # ------- variance BEFORE the update --------------------------
        denom = (a[s_t, a_t] + b[s_t, a_t])**2 * (a[s_t, a_t] + b[s_t, a_t] + 1)
        var   = (a[s_t, a_t] * b[s_t, a_t]) / denom
        var_list.append(var)

        # ------- Beta update -----------------------------------------
        a[s_t, a_t] += c_t          # success = common
        b[s_t, a_t] += 1 - c_t      # failure = rare

    df_out = df.copy()
    df_out["trans_var"] = var_list
    return df_out, a, b

In [ ]:
beta_transition_variance_conj(df, n_states=2, n_actions=2, a0=1.0, b0=1.0)

In [2]:
dataset

,Unnamed: 0,subj_idx,rt1,rt2,response1,response2,state1,state2,feedback,trial,cond,q_init,isleft1,isleft2,split_by
0,1,0.0,1.139,1.345,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.5,1.0,0.0,1.0
1,2,0.0,0.781,1.268,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
2,3,0.0,0.439,1.879,0.0,1.0,0.0,1.0,0.0,2.0,1.0,0.5,1.0,1.0,1.0
3,4,0.0,0.892,1.111,1.0,0.0,0.0,1.0,0.0,3.0,1.0,0.5,0.0,1.0,1.0
4,5,0.0,0.479,0.964,0.0,1.0,0.0,0.0,0.0,4.0,1.0,0.5,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29525,29526,107.0,0.411,0.366,1.0,1.0,0.0,0.0,1.0,292.0,1.0,0.5,0.0,1.0,1.0
29526,29527,107.0,0.688,0.802,1.0,1.0,0.0,1.0,0.0,293.0,1.0,0.5,1.0,0.0,1.0
29527,29528,107.0,0.328,0.340,0.0,0.0,0.0,0.0,0.0,294.0,1.0,0.5,1.0,0.0,1.0
29528,29529,107.0,0.308,0.399,1.0,1.0,0.0,1.0,1.0,295.0,1.0,0.5,1.0,0.0,1.0
29529,29530,107.0,0.648,0.513,1.0,1.0,0.0,1.0,1.0,296.0,1.0,0.5,0.0,1.0,1.0

In [ ]:




# ---------------------------------------------------------------------
# 1. Build centred (and optionally orthogonalised) predictors ----------
# ---------------------------------------------------------------------
# --- (a) z-score "general" uncertainty
dataset["unc_gen_c"] = (
    (dataset["uncertainty_general"] - dataset["uncertainty_general"].mean())
    / dataset["uncertainty_general"].std()
)

# --- (b) z-score "piecemeal" uncertainty
dataset["unc_piece_c"] = (
    (dataset["uncertainty_piecemeal"] - dataset["uncertainty_piecemeal"].mean())
    / dataset["uncertainty_piecemeal"].std()
)

# ------- OPTIONAL: orthogonalise piecemeal vs. general ----------------
# If you set USE_ORTHO = True the piecemeal predictor is residualised
# against the general one, removing collinearity.
USE_ORTHO = False

if USE_ORTHO:
    X = sm.add_constant(dataset["unc_gen_c"])
    resid = sm.OLS(dataset["unc_piece_c"], X).fit().resid
    dataset["unc_piece_c"] = (resid - resid.mean()) / resid.std()

# ---------------------------------------------------------------------
# 2. Define the 't' parameter with separate regression slopes ----------
#    (random intercepts & random slopes for BOTH predictors) ----------
# ---------------------------------------------------------------------
t_param = hssm.Param(
    "t",
    formula = (
        "t ~ 1 + unc_gen_c + unc_piece_c "
        "+ (1 + unc_gen_c + unc_piece_c | participant_id)"
    ),
    prior   = {
        # -------- group (population) means --------
        "Intercept":    hssm.Prior("TruncatedNormal",
                                   lower=0.01, upper=2.0, mu=0.20, sigma=0.10),
        "unc_gen_c":    hssm.Prior("Normal", mu=0.00, sigma=0.15),
        "unc_piece_c":  hssm.Prior("Normal", mu=0.00, sigma=0.15),
        # -------- SDs of the random effects --------
        "Intercept_sd":     hssm.Prior("HalfNormal", sigma=0.20),
        "unc_gen_c_sd":     hssm.Prior("HalfNormal", sigma=0.20),
        "unc_piece_c_sd":   hssm.Prior("HalfNormal", sigma=0.20),
    },
    link = "identity",               # use "softplus" if you need hard positivity
)

# ---------------------------------------------------------------------
# 3. Other parameters (unchanged from your earlier model) --------------
# ---------------------------------------------------------------------
alpha_param = hssm.Param(
    "rl.alpha",
    formula = "rl_alpha ~ 1 + (1 | participant_id)",
    prior   = {"Intercept": hssm.Prior("TruncatedNormal",
                                       lower=0.01, upper=1.0, mu=0.30, sigma=0.10)},
)
scaler_param = hssm.Param(
    "scaler",
    formula = "scaler ~ 1 + (1 | participant_id)",
    prior   = {"Intercept": hssm.Prior("TruncatedNormal",
                                       lower=1.0, upper=4.0, mu=1.50, sigma=0.40)},
)
a_param  = hssm.Param("a",  formula="a ~ 1 + (1 | participant_id)",
    prior={"Intercept": hssm.Prior("TruncatedNormal",
                                   lower=0.30, upper=2.50, mu=1.00, sigma=0.25)})
z_param  = hssm.Param("z",  formula="z ~ 1 + (1 | participant_id)",
    prior={"Intercept": hssm.Prior("TruncatedNormal",
                                   lower=0.10, upper=0.90, mu=0.20, sigma=0.10)})
theta_param = hssm.Param("theta", formula="theta ~ 1 + (1 | participant_id)",
    prior={"Intercept": hssm.Prior("TruncatedNormal",
                                   lower=0.00, upper=1.20, mu=0.30, sigma=0.15)})
w_param = hssm.Param("w",   formula="w ~ 1 + (1 | participant_id)",
    prior={"Intercept": hssm.Prior("TruncatedNormal",
                                   lower=0.10, upper=0.90, mu=0.20, sigma=0.10)})

# ---------------------------------------------------------------------
# 4. Instantiate the hierarchical SSM ---------------------------------
# ---------------------------------------------------------------------
hssm_model = hssm.HSSM(
    data            = dataset,
    model_config    = model_config,
    p_outlier       = 0,
    lapse           = None,
    loglik          = logp_jax_op,            # your custom RL-DDM likelihood
    loglik_kind     = "approx_differentiable",
    noncentered     = True,                   # robust default for few trials/pp
    process_initvals= False,
    include         = [
        alpha_param, scaler_param, a_param, z_param,
        theta_param, w_param,
        t_param,                        # <-- our new spec with two predictors
    ],
)

# ---------------------------------------------------------------------
# 5. Sample ------------------------------------------------------------
# ---------------------------------------------------------------------
idata = hssm_model.sample(
    draws           = 2000,
    chains          = 4,
    target_accept   = 0.9,          # ↑ a bit if you still see divergences
    max_treedepth   = 15,
)

# ---------------------------------------------------------------------
# 6. Posterior utilities ----------------------------------------------
# ---------------------------------------------------------------------
# population-level slopes
beta_gen   = idata.posterior["t_unc_gen_c"]
beta_piece = idata.posterior["t_unc_piece_c"]

# participant-specific slopes (non-centred reconstruction)
beta_gen_i = (
    beta_gen
    + idata.posterior["t_unc_gen_c_offset"]
      * idata.posterior["t_unc_gen_c_sigma"]
)   # dims: chain × draw × participant_id